dir_sequences: sequences

kmer: 8
mask: "11111111"
neighbors: 11
preprocessing: clip_scale_zero_one
percentile_clip: 100

path_encoder: /home/koke/Servers/watson/Github/panspace/indexes/8mer-mask11111111/triplet_semihard_loss-ranger-0.5-hq-128-CNNFCGR_Levels-level1-clip100/checkpoints/weights-CNNFCGR_Levels.keras
path_index: /home/koke/Servers/watson/Github/panspace/indexes/8mer-mask11111111/triplet_semihard_loss-ranger-0.5-hq-128-CNNFCGR_Levels-level1-clip100/index/panspace.index
outdir: test-query/

gpu: False
kmc_threads: 2

# for faster queries. Only used by query_fast.smk
fcgr_bin: /data/proj/panspace-paper/fcgr-mask/fcgr/fcgr
