dir_sequences: "/data/proj/panspace-paper/gsearch/data/sequences"
subset: "test"
outdir: "/data/proj/panspace-paper/panspace-data/fcgr-mask"
kmc_threads: 2

# for faster queries. Only used by query_fast.smk
bin_fcgr_mask: "/data/proj/panspace-paper/panspace-data/fcgr/fcgr"
mask: 
  # - "11111111"
  - "111100000001111"
  - "111100011000011"
  - "111100011010001"
  - "111000101010101"