import argparse
from rich_argparse import RichHelpFormatter

from fcgr.fcgr_from_kmc import FCGRKmc
import numpy as np
from pathlib import Path

## Parser
parser = argparse.ArgumentParser(
            description="generate FCGR", 
            prog="fcgr", 
            formatter_class=RichHelpFormatter
            )
parser.add_argument("-k", "--kmer", dest="kmer", type=int, default=6,
                     help="kmer size, the FCGR will be of size (2^kmer,2^kmer). Default 6"
                    )
                
parser.add_argument("--path-kmc", dest="path_kmc", type=str, default=None, required=True,
                    help="Path to kmer count generated by KMC"
                    )

parser.add_argument("--path-save", dest="path_save", type=str, default=None, required=True,
                    help="path to save FCGR"
                    )

args = parser.parse_args()

if __name__=="__main__":

    fcgr = FCGRKmc(args.kmer)
    m = fcgr(args.path_kmc)
    Path(args.path_save).parent.mkdir(exist_ok=True, parents=True)
    np.save(args.path_save, m)